#ifndef RF_VOXY_IRIS_INJECTED_GLSL
#define RF_VOXY_IRIS_INJECTED_GLSL

#define FOG_RANGE_UNIFORMS
#define RAIN_STRENGTH_UNIFORM
#define FRAME_TIME_COUNTER_UNIFORM
#define SUN_POSITION_UNIFORM
#define MOON_POSITION_UNIFORM
#define EYE_BRIGHTNESS_SMOOTH_UNIFORM
#define FOG_COLOR_UNIFORM
#define SKY_COLOR_UNIFORM
#define NOISETEX_UNIFORM
#define VOXY_RANGE_UNIFORM
#define RF_VOXY_UNIFORMS
#define TRANSFORMATIONS_UNIFORMS

#endif
